version: '3.8'

services:
  key-value-cache:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: key-value-cache
    ports:
      - "7171:7171"
    restart: unless-stopped